export const FETCH_TODOS_LOADING = 'FETCH_TODOS_LOADING'
export const FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS'
export const FETCH_TODOS_ERROR = 'FETCH_TODOS_ERROR'
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE'
